version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: tg-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  tg-ingestor:
    build:
      context: .
      dockerfile: services/tg-ingestor/Dockerfile
    container_name: tg-ingestor
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    secrets:
      - telegram_api_id
      - telegram_api_hash
    environment:
      - QUEUE_TYPE=redis
      - QUEUE_URL=redis://redis:6379/0
      - TELEGRAM_SESSION=/app/data/session.session
      - LOG_LEVEL=INFO
    volumes:
      - ./services/tg-ingestor/config.yml:/app/config.yml:ro
      - tg_session_data:/app/data
    healthcheck:
      test: ["CMD", "python", "app.py", "healthcheck"]
      interval: 60s
      timeout: 15s
      retries: 3

secrets:
  telegram_api_id:
    file: ./secrets/telegram_api_id.txt
  telegram_api_hash:
    file: ./secrets/telegram_api_hash.txt

volumes:
  redis_data:
    driver: local
  tg_session_data:
    driver: local