# Telegram Ingestor Service Configuration

# Telegram API configuration
telegram:
  session: "/app/data/session.session"  # Path to Telethon session file
  device_model: "tg-ingestor"
  system_version: "1.0"
  app_version: "1.0"
  flood_sleep_threshold: 60 

# Chat monitoring configuration
chats:
  ids:
    - 4816535195

# Bootstrap configuration (historical messages)
bootstrap:
  lookback_hours: 12  # Fetch messages from last 12 hours on startup
  enabled: true  # Whether to perform bootstrap
  max_messages_per_chat: null  # No limit by default

queue:
  type: "redis"
  queue_name: "telegram_events"
  config:
    url: "redis://redis:6379/0"
    dedup_ttl_seconds: 604800
    maxlen_approx: 1000000
    max_connections: 10
    socket_timeout: 5.0
    socket_connect_timeout: 5.0
# Security configuration

security:
  shared_token_file: "/run/secrets/queue_token"

# Message processing configuration
processing:
  max_concurrent_messages: 10
  allow_bots: true
  max_text_length: 16384
  min_text_length: 1

# Logging configuration
logging:
  level: "INFO"
  json_format: true
  enable_correlation: true